#!/usr/bin/python3

import sys
import os

def main(tag):
    dockerfile = "Dockerfile.{}".format(tag)
    print("Building and running: {}".format(tag))
    build_command = "DOCKER_BUILDKIT=1 docker build -t {} -f {} --ssh github={} .".format(
        tag,
        os.path.join(os.environ["DOUP_SEARCHDIR"], dockerfile),
        os.path.join(os.environ["HOME"], ".ssh/id_rsa")
    )
    print(build_command)
    os.system(build_command)
    run_command = "docker run -v {}:/home/devuser/.ssh --rm -it {}".format(
        os.path.join(os.environ["HOME"], ".ssh"),
        tag
    )
    print(run_command)
    os.system(run_command)
    os.system("docker rmi {}".format(tag))
    print("Success.")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Error: Requires exactly one argument!")
        sys.exit(1)
    main(sys.argv[1])


